runtime: php72
handlers:
- url: /(.*\.(gif|png|jpg|css|js))$
  static_files: public/\1
  upload: public/.*\.(gif|png|jpg|css|js)$

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
env_variables:
  APP_NAME: Awesome Cryptic Hunt
  APP_KEY: base64:zDOYuAltRdjlLy6XM9brS5BkVgo1eQSaA2TYx2ZhfO8=
  APP_ENV: production
  APP_DEBUG: false
  GOOGLE_CLIENT_ID: 415554013933-1nq6p8al49vquq2s1siqnnj7cpijs49s.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: ZGla7M7686uMstcNAHvBMnV2
  GOOGLE_CLIENT_CALLBACK: https://awesomecryptichunt.appspot.com/login/callback
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie
  DB_DATABASE: awesomecryptichunt
  DB_USERNAME: awesomecryptichunt
  DB_PASSWORD: ilikeawesomecryptichunts
  DB_SOCKET: "/cloudsql/awesomecryptichunt:asia-south1:awesomecryptichunt"